[package]
name = "humangl"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.34.5", features = ["bundled", "static-link"] }
failure = "0.1.8"
gl = { path = "lib_gl/gl" }
render_gl_derive = { path = "render_gl_derive"}

[features]
gl_debug = ["gl/debug"]

[build-dependencies]
walkdir = "2.3.2"