[package]
name = "gl_render"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
resources = { path = "../resources" }
gl_builder = { path = "../gl_builder" }